name: front end pipeline
on:
  workflow_dispatch:
jobs:
  build-and-test:
    name: build angular app
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node_version: ['18.x', '20.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout source code
      - uses: actions/checkout@v6   # checkout -> feature that allows you to clone a repository into the workflow's runner
        with:
          fetch-depth: 0
      - name: Setup Node            
        uses: actions/setup-node@v4 # To use an action, you must specify the repository that contains the action. 
        with:
          node-version: ${{ matrix.node_version }}
      - name: npm install, build and test
        working-directory: ./movies-ui
        run: |
          npm install
          npm run build --if-present
          npm test
