name: front end pipeline
on:
  workflow_dispatch:
jobs:
  build-and-test:
    name: Build and Test Angular App on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      APP_ENV: "development"
     # BUILD_NUMBER: ${{ github.run_number }}
    strategy:
      matrix:
        node_version: ['18.x', '20.x']
        os: [ubuntu-latest]
    steps:
      # ---------------------------------------------------------
      # 1) Checkout
      # ---------------------------------------------------------
      - name: Checkout source code
        uses: actions/checkout@v6   # checkout -> feature that allows you to clone a repository into the workflow's runner
        with:
          fetch-depth: 0
      # ---------------------------------------------------------
      # 2) Setup Node + Cache
      # ---------------------------------------------------------
      - name: Setup Node            
        uses: actions/setup-node@v4 # To use an action, you must specify the repository that contains the action. 
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
          cache-dependency-path: movies-ui/package-lock.json
       # ---------------------------------------------------------
      # 3) Install dependencies,build and test
      # ---------------------------------------------------------
      - name: npm install, build and test
        working-directory: ./movies-ui
        run: |
          npm install --force
          npm run build --if-present
          npm test
      # ---------------------------------------------------------
      # 4) Print environment variables within job scope
      # ---------------------------------------------------------
      - name: print environment variable
        run: |
          echo "APP_ENV is $APP_ENV"
          echo "current branch is ${{ github.ref_name }}"
  report:
    name: code-coverage report
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
       - name: Generate Coverage Report
         working-directory: ./movies-ui
         run: |
          npm run test:coverage
       - name: Upload coverage report
         uses: actions/upload-artifact@v4
         with:
          name: coverage-report
          path: movies-ui/coverage
  greeting:
    name: greeting the user
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
     - name: printing message
       run: |
         echo "Hello ${{ github.actor }}!Your pipeline ran successfully."
  practice-matrix:
    name: learning and practicing matrix concepts
    runs-on: ubuntu-latest
    needs: [build-and-test,greeting]
    strategy:
      matrix:
        user: ['ivan','maria']
        action: ['eating','sleeping','running']
    steps:
      - name: show matrix data
        run: |
          echo "User ${{ matrix.user }} is ${{ matrix.action }}"
  
